# Diary

## 2020

### May
    * [2020-05-19](2020-05-19)


## Task List

### Short-term
    * [O] Evaluation database
        * [X] Presentation on evaluation database and how we could make it work
          for Maziar and Minh.
            * [X] Minh suggests including all excluded fields except for
              reviewer title.
        * [X] RShiny application for data entry and retrieval
        * [X] Rmarkdown evaluation forms
            * [X] Long
            * [X] Short
        * [ ] Process for adding RShiny data to evaluation database
            * [ ] Selecting only the most recent record for repeat submissions.
            No automated process. Will need to write a custom import script
            identifying the desired rows each time a report is written. Or
            manually copy, though the former is reproducible.
    * [.] Finalize annual report
        * [O] Respond to public comments
            * [X] Read responses to comments from previous reports
                * [X] 2007, Appendix 5
                * [X] 2010, Appendix 4
            * [X] Read OAL guidance on public comments
            * [X] Respond to comments from PREC committee presentation,
              available on Youtube as of 6/3/20
            * [X] Respond to written comments
            * [ ] Meet with management, then revise Edgar's comments.
        * [o] Check hypothetical emissions
            * [X] Does annual report script use lbs AI or product?
                * [X] It uses lbs AI in Rmd report
            * [ ] What about past master workbooks?
        * [ ] VOC listserv / stakeholder email
        * [ ] Archive any folders that have changed
        * [ ] Did I document the issues with the ARB submission in the
          procedures? I think I added a README file. See 4/28 email
    * [o] Data submission to ARB
        * [X] Complete steps in procedureal document
        * [ ] Burn to CD
        * [ ] Submit to ARB
        * [X] Update procedural document
    * [.] VCS for SAS scripts
        * [X] Add git bare repo to serve invnetory scripts.
        * [ ] Add git bare repo for annual report scripts and those used to make
          script input datasets.
        * [ ] Reinstall Git for Windows and move repo to A:
        * [ ] Add instructions for using repo
        * [ ] Add tags for each inventory run (e.g., 2018PrelimDraft,
          2019AnnualFinal)
    * [ ] Preliminary report
        * [ ] Conversion to rmarkdown
            * [ ] Make annual report code modular through source() or child
            * [ ] ggplot refactoring
            * [ ] Reuse annual report code
            * [ ] Discussion and updates around chlorpyrifos?
        * [ ] Update instructions
    * [ ] Brenna's Focus 4 email
    * [ ] Decision for Registration on changing TGA eval forms
    * [ ] Eval database template
        * [ ] Flag products that are missing evaluations
        * [ ] Flag evals that are missing entries in db
    * [ ] Finish updating evaluation guidelines
    * [ ] Document ongoing projects and consolidate meeting notes and emails
      from Registration
    * [ ] SOP for Air Program-Registration data process, in particular ABNs and
      product transfers

### Long-term

    * Convert inventory guidelines to markdown and version control
    * Script rewrites
        * Topics
            * Unadjusted emissions
                * Two scripts calculate unadjusted fumigant emissions differently,
                  one of which is used for adjusted emissions. Need to confirm that
                  scripts' results are the same for these fumigants, or else how
                  differences affect final inventory results and whether to rewrite.
                  See "D:\EmissionsCalcs.docx";
                  "D:\EmissionsCalculationAnalaysis.xlsx";
                  Compare_Unadjusted_Calcs.sas
            * Adjusted emissions (A/VOC/Procedures/Adjusted emissions.docx)
            * Errors in aggregated totals
                * Seen in AI and site-AI totals, and in differences between mebr
                  and nonmber datasets. See Rmarkdown report, roadmap, and
                  procedural document for report.

                  In general, aggregation should be done as late as possible in
                  the data process to avoid loss of information and unnecessary
                  early splitting of a dataset into multiples, which increases
                  the risk of truncation and other i/o errors. Aggregation
                  across one group of factors should be done only once for each
                  dataset.
    * SOP for updating inventory inputs
    * Script to identify Focus-4 products
    * Update flowchart to reflect new inventory process, once finalized
        * Add to inventory script git repo

#### Miscellaneous

    * Statewide calculations
    * Organize archived historical files


### Recurring

    * TGA reviews
        * Archive submissions to evalreports
            * See procedural document on new archive process
        * Keep a running list of products to add to each inventory run
    * Focus 4 lists
        * Record changes that should be added to the VOC inventory
        * ADA conversion for each list
        * IT ticket to post each list
    * Product name and regno update letters from Brenna
        * Add to product evaluation file to help check filename (CA regno) with
          contents
    * [ ] Add and populate bridge-indicator variable in EP database and tracking
      sheet
        * [ ] For information on past bridges, see evaluations, past tracking
          sheets, and comment variables in the EP and tracking sheets
    * Preliminary report
    * Annual report
        * Modify script
        * Run report and check for issues
        * Management edits
        * Executive edits
        * ADA conversion
        * Public comment period
        * Resolve public comments
        * Modify script
        * Run report and check for issues
        * ADA conversion
        * Publish report
