# 2018-09-04

Minh sent Kelsey and I Cheryl's 2018-08 procedures for logging incoming
evaluations, outgoing evaluation reports, and EPs in two tracking spreadsheets.

Kelsey requested an Air Program meeting to review evaluation procedures with
staff. She included a copy of the current internal guidelines for constructing
evaluation reports. She noted that Cheryl's document doesn't name the
spreadsheets. "VOC Spreadsheet.1.30.2018.xlsx" is the name of Spreadsheet I (the
evaluation tracker), and "TGA_data_entry_from_Cheryl_1.30.18.xlsx" is the name
of Spreadsheet II (the EP tracker). Kelsey suggested eliminating Cheryl's role
(evaluation and EP tracking) and combining it with her own role (overseeing
and reviewing staff evaluations).

# 2018-09-12

I informed Minh that Kelsey and I planned to create a "master EP database" by
combining Cheryl's tracking and our current EP spreadsheets. We brok the task
down into defining database structure, cleaning and merging the spreadsheets,
data entry into Access, and ongoing data validation. I anticipated starting the
project after completing the 2017 annual inventory (i.e., sometime in late
2018/early 2019). Minh agreed with the project and timeline.

# 2018-09-13

Cheryl sent Kelsey an "old" spreadsheet from 2005: "VOC.Reformulation Worksheet
Status.1.9.09.xls". The date and mention of reformulation brings to mind a
Notice from that year requiring reformulation of liquid ag pesticides. A number
of our evaluations from that time also reference reformulation. I believe Kelsey
sometimes referred to this as Spreadsheet III.

See also A:\VOC\Emissions_Potential\TGA_Evaluations\_ReformulationEvaluations,
"A:\VOC\Archive\VOC reformulation reevaluation", and anything that pops
up under a search of A:/VOC for "reformulation."

# 2019-02-26

I emailed Rosemary about this project. I clarified that I planned to separate
data, metadata, and tracking/changelog. I asked her the following questions:

1. Purpose of "merge_reeval_TGA_EPs_with_EPdatabase.mm.yyyy.[in]active$TGA
   reeval assignment procedure"?
2. Related to all of our EP database-related files, I am looking for more
   information on several method codes/descriptors: bridged (0), tga/derived
   (2), derived (7), and CSF (8).
    a. Is there any conceptual difference between codes 0 and 7? (I am thinking
    of adding a new variable that indicates bridges, specifically the prodno of
    the original product from which we bridged. So I want to know whether there
    are any special considerations for method code 0.)
    b. Our method-code key in our workbooks indicates that code 7 determinations
    are made only by Registration. EM has filled out TGA evaluation forms
    approving bridges for substantially similar products. From what I have seen
    (e.g., prodno 62582), we use the code (1) for TGA evaluations, rather than
    code 7, to indicate bridges that EM approves, but I had trouble finding
    other EM bridges to verify this. Do we only use code 1 to indicate some
    products for which EM has done SS comparisons, or do we also use code 7?
    c. How do I know when a product should be added under method code 2? I had
    thought this was a legacy code, and indeed most such products seem to have
    been added by Frank. But there were some added by Kelsey and you, so I
    figure I need to be on the lookout for these liquid call-in products.

Rosemary's response:

1. This is something Frank would have written, probably to document the
   procedure he followed at the time. I agree that it can be removed.
2. You may have seen the attached document [inventory4.docx] that
   Frank authored back in 2012. It describes the method codes starting on page
   four. [NOTE: This is an older version of the background document Kelsey
   passed on to me.]
    a. Most of the products with code 0 seem to have had their EP derived from
    one master label product MASTER LABEL - CONCORDE P-40. I’m not sure why
    Frank used 0 as opposed to 7 – perhaps he can remember. If you add a new
    variable – which I agree sounds like a good idea – I would recommend you
    keep the “old” code variables in case you need to refer back to them at some
    point.
    b. Code 1 should be used just for TGA evaluations and Code 7 for
    substantively similar/AB1011 equivalence process. If you find products which
    appear to be incorrectly coded, I would suggest you update them. Again –
    keep a copy of the “old” code for reference.
    c. According to Frank’s notes code 2 was used to identify multiple
    subregistrations for which only one product was actually tested. I think it
    would be useful to retain this code. Now would be the time to thoroughly
    document all the codes because – as you have probably figured out – it can
    become very complicated.

My response:

2.b. To clarify, if EM does an SS/AB1011 bridge and fills out an evaluation form
for the bridge, that would be indicated by code 7? The only such form I found
was labeled code 1, and I have had trouble finding counter-examples.

2.c. I saw some code-2 products with comments in this style:
‘Jun_2017_RN_from_Carlos_Gutierrez.’ The ‘RN’ initials made me suspect that
these were products you had added. I was wondering if you remembered any of
these products and if so, how you knew to add them under method code 2.

Rosemary's response:

2.b. I would agree with you – whether the bridge originates in Registration or
EM, the code should be 7.

2.c. Yes – RN was me!! The Stallion products (279-9545-): AA submitted TGA data
(code 1), sub-registration ZA did not (code 2). According to Carlos in
Registration Minx 2 (228-736-AA and 228-734-ZA; code 2) and were
subregistrations of Abamex (228-734-AA, originally called Nufarm Abamectin 0.15
LVOC; code 1) for which TGA data was submitted.
