---
title: "R ggplot2"
---

TODO: Add to this by reading
https://ggplot2-book.org

TODO: Use geom_hline instead of geom_line for a dataset variable
TODO: Use scale_*_identity and a data variable for thresholds in figures
TODO: Use a base ggplot object and `+ aes(...)` and `%+% <data>` instead of
repeated functions calls. Use your knowledge of scales and theme to simplify
figures.
TODO: Source sections of the report to reduce size if possible

Every use of ggplot2 begins with a call to ggplot() followed by one or more
calls to geom and stat layers; scales; themes; coords; annotations
and/or facets. separated by the `+` infix operator.

= Primary functions =

ggplot(df, aes(x,y,...))    Set the default data for all layers to plot and
                           aesthetics. Data and aesthetics can be overridden in
                            individual layers. No defaults need be provided, so
                            ggplot() is a valid function call.

aes(x,y,...)                Create an aesthetic mapping. Aesthetic mappings
                            describe how data variables map to visual properties
                            of geoms. The arguments to aes() are name-value
                            pairs in the form `aesthetic=variable`, though x
                            and y (if x is present) may be given as positional
                            arguments. Variables are evaluated within the
                            context of the layer's data (the default data if no
                            layer data is specified). Variables may also be
                            expressions involving variables or constants.

e1 + e2                     Used to add plot components to a theme or ggplot
                            object. Components can be an *aes() object to*
                            *override the default aesthetics*, a layer (geom,
                            stat, or position-adjustment), a scale, a theme, a
                            coord, or a facet.

e1 %+% e2                   Used to *override the default data* of a ggplot
                            object. `e2` is the new default data to use.

ggsave                      Save a plot, by default the last plot displayed.

= Example =

This example shows three ways of specifying different mappings for different
datasets. ds and df contain a common variable (gp) for the x-axis but different
variables (y and mean) for the y-axis.

{{{r
 # Generate some sample data, then compute mean and standard deviation
 # in each group
df <- data.frame(
   gp = factor(rep(letters[1:3], each = 10)),
   y = rnorm(30)
)
ds <- do.call(rbind, lapply(split(df, df$gp), function(d) {
   data.frame(mean = mean(d$y), sd = sd(d$y), gp = d$gp)
}))

 # The summary data frame ds is used to plot larger red points on top
 # of the raw data. Note that we don't need to supply `data` or `mapping`
 # in each layer because the defaults from ggplot() are used.
ggplot(df, aes(gp, y)) +
   geom_point() +
   geom_point(data = ds, aes(y = mean), colour = 'red', size = 3)

 # Same plot as above, declaring only the data frame in ggplot().
 # Note how the x and y aesthetics must now be declared in
 # each geom_point() layer.
ggplot(df) +
   geom_point(aes(gp, y)) +
   geom_point(data = ds, aes(gp, mean), colour = 'red', size = 3)

 # Alternatively we can fully specify the plot in each layer. This
 # is not useful here, but can be more clear when working with complex
 # mult-dataset graphics
ggplot() +
   geom_point(data = df, aes(gp, y)) +
   geom_point(data = ds, aes(gp, mean), colour = 'red', size = 3) +
}}}

= Layers =

*Unlike ggplot(), layers have aes() as their first argument, so data*
*must be a named argument to be used in the first position.*

== Geoms ==

Described as a combination of data, aesthetic mapping, a geometric object, a
statistical transformation, and a position adjustment.

== Stats ==

Some of these are specified as layers to be called in lieu of geoms, while
others are shown in the documentation as the value of a geom's `stat`
argument--not as a function call but as a string that isn't always the full
function name. It is unclear if the functions can be used as well.

== Position ==

Though the documentation initially seems to classify these as independent
layers, they are only ever used as the value of arguments to a geom in the
examples. In some cases, these may be specified as string arguments to the
position argument of a geom; however, the function calls as the value of
position seem more common. Unlike stats, these don't ever seem to be used in
lieu of a geom.  Some examples show helper functions that can replace a position
function call with an argument (e.g., position_nudge and nudge_y).

Functions like position_dodge can be used to position overlapping objects such
as bar charts that share the same point on the x-axis. position_dodge requires
the group aesthetic. I have not tested yet whether other aesthetics can fill in
for the group aesthetic, or whether the latter must be explicitly included.

== Annotations ==

See abline, hline, and vline.

= Aesthetics =

Individual aesthetics are the arguments passed to aes().  Note that not all
aesthetic specs apply to each layer. The layer's help doc should list the
applicable args to aes(). E.g., the geom_map layer doesn't accept x and y
aesthetics but does require x and y columns in the dataset passed to its map
arg.

See [[https://ggplot2.tidyverse.org/articles/ggplot2-specs.html]] for a guide to
aesthetics common to many layers.

== Data types ==

Most aesthetics map to discrete variables.

x and y map to continuous, discrete, and date/time/datetime variables. There is
a scale for converting continuous to binned data: `scale_(x|y)_binned`.

Colour and fill also map to binned and continuous variables, which makes sense
given that the color scale can be represented as individual colors or as a
gradient.

Alpha provides a continuous function that does nothing but abort and
provide a warning message, while its discrete function shares a warning and
secretly calls the ordinal function. Alpha is the only aesthetic with an ordinal
function, perhaps because it is the only aesthetic that is commonly represented
as a numeric scale, from 0 (transparent) to 1 (opaque).

Size has a binned scale that can be used to assign sizes to continuous data.
Other aesthetics like shape and linetype offer binned functions as well but warn
that they shouldn't be used because, unlike continuous data, shape and linetype
don't have an inherent order.

=== Discrete data ===

Discrete data seems to encompass both numeric-discrete and categorical-nominal
data. In most cases, it likely also encompasses categorical-ordinal data, though
the alpha scales treat ordinal data separately from other discrete data.

== Group ==

ggplot creates groups based on any discrete (categorical?) variables mapped to
the axes (x and y aesthetics) or aesthetics such as shape and fill. These
groups, however, also affect statistical transformations such as boxplot and
smooth. For examples of this behavior, see
https://www.gl-li.com/2017/08/13/ggplot2-group-overrides-default-grouping/

This link gives the example of mapping color based to year. In the example,
there are two years and a categorical x-axis. Specifying a year-based color
doubles the number of boxplots. This may not be the desired behavior--what if
you want the original number of boxplots with year-based coloration of the
points within each boxplot?

It helps to look at the code in the link, but the cause in the example is that
the aesthetic specification is specified in ggplot() and thus inherited by every
layer, including stat_boxplot. The first example can be solved by moving
`color = factor(year)` to within a call to aes within geom_jitter. That way it
doesn't affect stat_boxplot.

Another solution involves overriding the default group within the desired layer.
E.g., stat_boxplot(aes(group=drv)) gives the desired grouping,
stat_boxplot(aes(group=interaction(drv, year))) recreates the default grouping,
and stat_boxplot(aes(group=123)) has no grouping. Notice that the use of a
constant instead of a variable eliminates grouping, leading to a single boxplot.
Note that multiple variables must be wrapped in a call to `interaction()`.

=== Comparison to ggplot2 docs ===

The package documentation doesn't explain any of the above; however, it provide
examples that confirm the above. In
https://ggplot2.tidyverse.org/reference/aes_group_order.html an example is given
for geom_line of grouping. With the default group based on age and height (i.e.,
no grouping because both variables are continuous), all points are connected by
a line. If group=Subject is used, however, only within-Subject observations are
connected by a line.

=== Individual vs collective geoms ===

In short, the group aesthetic only affects collective geoms (e.g., line, path,
boxplot), which display a single object for multiple rows, in contrast to
individual geoms (e.g., point). However, some geoms retain features of
individual geoms. E.g., a path composed of points with different colors will
have segments with different colors. In contrast, a polygon uses the same color
for all segments. See the link for a visual example of this.

See also [[https://rpubs.com/hadley/ggplot2-toolbox|this article by Hadley Wickham]]
for more on this topic, as well as a list of extensions to ggplot.

= Scales =

Scales detail how to map data variables to aesthetics. Unlike layers, there can
only be one particular type of scale at a time. Each call to the same scale
function will override the previous scale.

TODO: Test this with various helper functions and scales, both with similar and
different arguments. E.g.  labs(title=, subtitle=) and ggtitle() probably
override each other; as would labs(x=), xlabs(), and scale_x_continuous(name=).
At least I believe that the helper functions and scales can override each other.
It is unclear if only similar arguments override each other, or if each call to
a scale or helper function overwrites previous ones entirely.

Not all aesthetics have an associated scale function. The following do: alpha,
x, y, colour, fill, linetype, size/radius, and shape.

Scale functions are named as scale_<aesthetic>_<data-type> for the most part,
though many functions break with this convention by using aliases for data type
or omitting it altogether (i.e., the colour scales).

There are also scale functions that allow for exact specification of the mapping
between data types and the values/properties of an aesthetic: scale_*_manual and
scale_*_identity (see below).

== Ellipsis arguments ==

Most scales have positional arguments `...` that are passed on to an internal
function. The description of `...` specifies which function, and the source code
of a scale function and the function it calls reveal what those arguments are.

E.g., one example for `scale_alpha` passes a string as the only (positional)
argument. The source code of `scale_alpha` passes `...` as the fourth argument
to `continous_scale`, whose fourth argument is name.

E.g., labs() notes that its `...` is a list of name-value pairs, where the name
is the aesthetic. The value is a title for an axis (x or y) or a legend
(e.g., colour).

== Colour/fill scales ==

The color and fill aesthetics are categorized below because there are many
related scales whose data types are not always obvious from the scale names.

Several colour/fill scales support continuous, binned, and discrete data:
    * colorbrewer.org scales, ending in brewer, distiller, and fermenter
    * viridis scales

Continuous scales:
    * scale_*_continuous (defaults to gradient; can use viridis)
    * scale_*_gradient[2|n]

Binned scales:
    * scale_*_steps[2|n]

Discrete scales:
    * scale_*_grey
    * scale_*_hue

== Identity scales ==

Identity scales are provided for cases when you map an aesthetic to a variable
that holds values for the aesthetic.  Normally the value of a mapped variable
only indicates grouping, but aesthetic-valued variables can be used both to
group and control scaling.  There are identity scales for colour, fill, shape,
linetype, alpha, and size. There are also generalized identity scales for
discrete and continuous variables.  The generalized scales accept an aesthetics
argument and can be used to provide the same values to multiple aesthetics
(e.g.. colour and fill)

== Manual scales ==

If your dataset doesn't contain the values of the aesthetic but you still want
to create your own discrete scale, use scale_*_manual. Except for
scale_continuous_identity, all identity scales have a manual counterpart.  The
primary argument is a named vector, where the names are values of your variable
and the values are aesthetic values.

== Limits ==

Helper functions lims(), xlim(), and ylim() are shortcuts for the limits
argument to scale functions.

Using lims(), xlim(), ylim(), or the limits argument of the scale functions
replaces data outside of the limits with NA. To change axis limits without
dropping data, see coord_cartesian(). The difference shows up e.g. when using
geom_smooth and other statistical transformations.

lims() doesn't just affect x- and y-axes. It can also be used with grouping
variables to extend the axes beyond the values within the data.

{{{r
small <- subset(mtcars, cyl == 4)

ggplot(small, aes(mpg, wt, colour = factor(cyl))) +
  geom_point() +
  lims(colour = c("4", "6", "8"))
}}}

If you want to ensure that the axes include a certain point or range, use
expand_limits(). If the specified value(s) falls outside the data range, the
axes will be extended to include it/them. Otherwise, the axes are unchanged.
Like lims(), the extent of grouping variables can be specified. Unlike lims(),
the extent is not fixed and may be larger than intended if the dataset has a
larger range than that specified to expand_limits.

In contrast to expand_limits, expansion() is a helper function that is used with
the expand argument of the discrete and continuous scale functions to add
padding around the data. It accepts padding as a number of units or as a % of
the range. expand_scale() seems to be an alias.

= Guides =

Guides are axes, legends, and colour bars. They are the inverse of scales: they
provide a mapping from aesthetics to data; that is, a guide to interpreting
plots. Guides are automatically generated based on aesthetic mappings.

Guides are mostly controlled via scale functions (e.g., the name, limits,
breaks, and labels arguments). Additional control comes from the guide argument
of scale, guides(), and guide_*() functions.

To suppress a guide element, set it to NULL.

Axis title can be controlled through xlab, ylab, labs, or an x|y scale
function's name argument. Legend and colourbar titles can be controlled via labs
or the revelent aesthetic's scale function.

Breaks are legend keys and axis tickmarks. Labels are the text that appear next
to breaks.

If labels are set, breaks should also be explicitly set if there is a chance
that the data could change. If the data changes, labels could be inappropriate
for the changed default breaks. With numerical scales, you set the breaks and
labels. With categorical data, you don't set the labels. Instead you pass a
named vector to labels, where the names are the data values and the values are
the labels for the data values. (At least this is what the ggplot2-book.org
examples demonstrate.) TODO: I wonder if it is possible to mix and match these
different methods.

The labels and breaks arguments also accept functions. The breaks function
accepts a length-2 vector of limits and returns a breaks vector of any length.
The labels function accepts a length-n vector of breaks and returns a labels
vector of the same length. The scales package provides several label formatting
functions.

The minor_breaks argument is useful with e.g. log scales. See the example in
ggplot2-book.org.

== Legends ==

In contrast to axes, legends can display multiple aesthetics (e.g. color and
shape), from multiple layers, and the legend key/symbol depends on the type of
geom used (e.g. point or line); additionally, legends' position relative to the
rest of the plot is configurable. These options are controlled through

Layers only appear in the legend if an applicable aesthetic such as shape or
linetype is mapped to a variable in the layer's data. This can be changed for a
layer by show.legend. FALSE prevents it from appearing, while TRUE forces it to
appear. E.g., aesthetics don't show up in the legend if they are specified
within a layer but outside of aes() (as when setting an aesthetic to a constant
value), as in the first geom_point layer below:

{{{r
ggplot(df, aes(y, y)) +
  geom_point(size = 4, colour = "grey20") +
  geom_point(aes(colour = z), size = 2)

ggplot(df, aes(y, y)) +
  geom_point(size = 4, colour = "grey20", show.legend = TRUE) +
  geom_point(aes(colour = z), size = 2)
}}}

ggplot attempts to minimize the number of legends by combining aesthetics *for*
*the same variable into the same legend key.* This behavior is controlled by the
name argument of a scale. For merging to occur, the scales' name must have the
same value. Change name to split aesthetics out into their own legend. You can
also use the same name to combine guides (of the same or different type) for
different variables. See https://ggplot2.tidyverse.org/reference/guides.html

Some guide properties are specified through theme (e.g., legend.position,
legend.box, legend.box.just).

Other properties are controlled through guides() and guide functions.

If you want aesthetics to be displayed differently in the legend than in the
plot, see this example. The last line overrides the constant alpha of the plot
with a different constant. Note that the name within guides (colour) is an
aesthetic that has been mapped within aes to a data variable. My guess is that
you could specify any of the aesthetics included in a legend, if there were more
than just one aesthetic. Note also that the list of override.aes contains only
an aesthetic previously given a constant value (alpha).

{{{r
norm <- data.frame(x = rnorm(1000), y = rnorm(1000))
norm$z <- cut(norm$x, 3, labels = c("a", "b", "c"))
ggplot(norm, aes(x, y)) +
  geom_point(aes(colour = z), alpha = 0.1) +
  guides(colour = guide_legend(override.aes = list(alpha = 1)))
}}}

theme
    legend.position (position for bounding box)
    legend.box (how to stack legends within box)
    legend.justification (justification within bounding box)
Legends specified for each aesthetic:
scale_fill_continuous(guide = guide_legend())
guides(fill = guide_legend()) -> helper function for guide arg of scale*(),
    similar to labs()
guides
    guide_legend (discrete fill)
       ncol
       byrow
       reverse
    guide_colorbar (continuous fill)


The guides() function can be used to display the legend keys differently than
the plot does. E.g., the plot may use a higher transparency value than you want
in the legend.



WHAT ABOUT SHOW.GUIDE??????


= Facet =

Whereas many aesthetics create groups shown in the legend of a single plot and
in the plot itself, the facet_* functions create groups by splitting the data
between a number of plots shown on a grid.

= Scales =

Arguments to the continuous scale include name (axis or legend title), breaks
(tickmarks or legend key), labels (break or legend key labels), limits, expand
(padding), oob (behavior for data outside limits), na.value, trans
(transformations for the data, e.g.  log10 or reverse), position (l/r/t/b),
sex.axis (secondary axis). Note from the examples that labels accepts
transformation functions for numeric label formatting. See the scales package.

scale_[x|y]_discrete() works a bit differently with labels and limits when
dealing with factors. The labels argument allows you to rename the axis labels
by using a named vector. The names are the original values (in the data) and the
values are the new names you'd like. The order determines order on the axis.
Limits can be used to reorder a factor's levels' order on the axis and limit
which ones appear, without renaming them (see labels). The reorder()
function--see the help page examples--can also be used for reordering without
using the scale function.  Labels also accepts formatting functions like
base::abreviate for factors.




