# Shopping

    * Picture frames and hangers
    * Bike lubricant
    * Tube repair kit
    * L-theanine
    * Hair trimmer
    * Sowing equipment and thread

# iPhone apps (new phone)

    * heavyset
    * google maps
    * lyft
    * voyager
    * 1password
    * spotify
    * castboxs
    * euclidia
    * messenger
    * wells fargo
    * fedex
    * lemonade
    * affirm
    * paprika 3

    * quizlet
    * inaturalist
    * seek
    * sky guide
    * plant snap
    * merlin bird id
    * song sleuth
    * picturethis
    * dayone
    * okcupid
    * contacts
    * shortcuts
    * authenticator (for microsoft account)
    * calm (year subscirption)
    * roku
    * uhc
    * health4me
    * rsa ( work)
    * musescore
    * myhealthonline
    * gmail

# Board games
    * Incan gold
    * Rivals for Catan
    * Bananagrams
    * Hey that's my fish

# Car Dealers and Loans

https://www.carbuyingtips.com/car4.htm

Factory invoice will list base price of car and factory-based options;
optionally, it will list holdback and destination and advertising fees. The
actual price to the dealer will be the invoice price minus any unlisted
incentives (holdback and factory-to-dealer) and any fees listed on the invoice
(e.g., destination and manufacturer advertising) passed onto the consumer. To
figure out your offer: add 5% to this dealer price, then add fees (whether
listed or not). This is the price you will pay before any rebate and out the
door costs charged by the state and dealer. The rebate should NOT factor into
the negotiated car price; the manufacturer, not dealer, pays this. What the
consumer pays will be the negotiated price minus the rebate—assuming they give
the rebate to the dealer rather than having it mailed by check—plus out the door
costs. Make sure the dealer’s negotiated price is the out of pocket cost before
the rebate, rather than after using the rebate. The negotiated should be total
price the dealer receives—not your out of pocket costs, which may or may not
have the rebate factored into it. Legitimate out the door costs include vehicle
registration/title/license plate fees ($296), sales tax (10.25%), documentation
or conveyance or processing or service and handling fee (capped at $80) and
sales tax on doc fee, smog fee, and some dealer fees. Dealers may try to add
their own advertising fees. Be wary of these and verify you are only paying a
manufacturer advertising and fee, unless the dealer fee is low and you can
negotiate a low overall car price. Do not double-pay any fees.

Negotiate the price before out the door costs, then ask for a final out the door
number. Investigate the out the door costs to ensure they are all legit (see
above). Negotiate dealer fees in particular, as many of these may be unnecessary
or made up. If financing, consider financing offers only after figuring out the
price. Do not negotiate monthly payments—negotiate price first—because monthly
payments can be lowered by extending the term of repayment.  There may be
low-interest financing in addition to or if a rebate is not offered.
Alternatively, there may be a special leasing program available instead of
financing an outright purchase. Ask to see the factory invoice. Ensure it is a
legitimate factory invoice with the manufacturer logo on it, rather than a
dealer-generated invoice.

When comparing quotes, make sure to compare apples to apples by matching as many
of the options as possible across dealerships. Check the history of the vehicle.
After getting quotes electronically, take the cars for test rides. Any defects
can be used in negotiations. Have the car inspected before purchase, and use the
preport for negotiations or to request repairs prior to finalizing the deal.

Sources for holdback, incentives, and factory invoice (verify incentives and
fees these may include!):
Manufactuere websites
CarsDirect
Ryde Shopper
Motor Trend
Edmunds TMV (https://www.edmunds.com/tmv.html) . Also includes invoice price for comparison. TMV accounts for incentives and fees affecting transaction price (destination, advertising, dealer incentives, holdback(?)) but not out the door costs. So it can be used as an estimate of fair value negotiated price.
 - If leasing or buying used, see: https://www.edmunds.com/car-buying/how-to-use-tmv.html
Truecar
Kelley Blue Book
https://www.edmunds.com/car-buying/dealer-holdback/
https://www.autocheatsheet.com/new-car/dealer-holdback.html#holdback-chart

Sources for cars:
https://www.digitaltrends.com/cars/best-used-car-websites/

Also use the above sites to request quotes from Internet sales managers at
dealers, then compare to calculations of fair pricing for vehicles.

Additional fees/terms to avoid: https://www.carbuyingtips.com/new-car-buying/fee-glossary.htm
Negotiations advice: https://www.edmunds.com/car-buying/negotiating-101.html
Asking for and auditing an invoice: http://www.realcartips.com/newcars/177-see-dealer-invoice-negotiating.shtml

Green vehicles:
https://www.driveclean.ca.gov/pev/Costs/Vehicles.php
https://cleanvehiclerebate.org/eng/eligible-vehicles
https://ww3.arb.ca.gov/msprog/lct/cvrp.htm
https://www.green.ca.gov/fleet/Documents/147013-DGS-DriveGreen-2019-ADA.pdf
https://www.green.ca.gov/Fleet/drivegreen/FAQ

# Credit freezes

https://help.equifax.com/s/article/How-do-I-place-temporarily-lift-or-permanently-remove-a-security-freeze

# CAPS Benefits

$5000 in term life insurance
$5000 in accidental death and dismemberment insurance
$100,000 in travel accident coverage (covers public transportation with fares and loss on a scheduled airline flight)
Option to purchase additional term and long-term disability insurance
Option for Liberty Mutual Insurance for home and auto. Premiums paid via payroll deduction.
Travel Assist. This looks like an interesting resource for traveling abroad.
Discounts (including theme parks)

# Bad Elf GPS

Bad Elf GPS provides GPS without cell service needed: ‘All iPhones and some
iPads come equipped with access to the internet via the cellular phone data
network. These units also include “A-GPS. The “A stands for “assisted, as in
assisted by the cell towers. So if your iPhone/iPad (with cellular) has a
connection to the cell towers, the assisted GPS inside your iPhone/iPad will
work well enough for most activities. But away from the cell towers, up in the
sky, out in the woods, or at sea, the GPS can take 20 minutes or more to locate
you. Because Bad Elf GPS products rely only on the satellites orbiting the earth
and never on cell towers, they can locate you quickly and accurately anywhere on
the planet.’

Check out both bad elf gps products (insertable into ipod touch and wireless
communication) and the apps provided.

