---
title: "Neoterm structure"
---

# neoterm/autoload/neoterm.vim

neoterm#new (Tnew): Create a new terminal

neoterm#do (T): Executes a single command argument. Constructs a list of arg.cmd and g:neoterm_eof
    and passes it to neoterm#exec.

neoterm#exec (Texec): Executes a series of command arguments. Expands arg.cmd via s:expand. Retrieves
    (neoterm#target#get) or creates a new terminal (neoterm#new) in l:instance. l:instance.exec() is
    passed the expanded argument. If you look at the command:

    command! -range=0 -complete=shellcmd -nargs=+ Texec
          \ call neoterm#exec({ 'cmd': [<f-args>, ''], 'target': <count> })

    Note how the argument to pass is a dict and 'cmd' key is a list ending with the EOF character ("''").

    The default for Python is 'ipython --no-autoindent' if ipython is available
neoterm#repl#line (TREPLSendFile with default range of %; TREPLSendLine with default of current line):
    Sends range specified by arguments line1 and line2 to terminal/repl

= neoterm/autoload/neoterm/target.vim =
neoterm#target#get: Retrieves the terminal, I think

= neoterm/autoload/neoterm/repl.vim =
neoterm#repl#set: Sets the value of g:neoterm_repl_command.
neoter.repl.instance: Creates a new terminal if needed, then neoterm#repl#term on the last active terminal;
    otherwise, it returns an instance.
neoterm#repl#term (TREPLSetTerm): Sets the terminal. Then does neoterm#exec with g:neoterm_repl_command if
    g:neoterm_auto_repl_cmd is set.
g:neoterm.repl.exec: Calls neoterm.repl.instance(), then uses the returned terminal's exec() function to
    execute a command list appened with neoterm_eof

neoterm#repl#selection (TREPLSendSelection): Send selection to repl
" REPL selection mappings
nnoremap <silent> <Plug>(neoterm-repl-send)
      \ :<c-u>set opfunc=neoterm#repl#opfunc<cr>g@
xnoremap <silent> <Plug>(neoterm-repl-send)
      \ :<c-u>call neoterm#repl#selection()<cr>
nnoremap <silent> <Plug>(neoterm-repl-send-line)
      \ :<c-u>set opfunc=neoterm#repl#opfunc<bar>exe 'norm! 'v:count1.'g@_'<cr>


