---
title: "Spacevim"
---

## Autoloading

The call to autoloaded function myplugin#somefile#Hello() searches inside
~/.vim/autoload/myplugin/somefile. In other words, an autoloaded function
is defined and called with prefixes representing the path relative to
~/.vim/autoload/. To explicitly source an autoloaded file to get access
during init.vim, use the runtime command with a path relative to an entry in &rtp
(e.g., runtime autoload/clap/providers/buffers.vim).

## Project Layout

Aside from the SpaceVim main repository, there are also repositories for:
- ctrlp
- unite[-ctags|-unicode]
- denite
- gtags
- luacomplete
- vim-material
- vim-lookup

### The main repository's structure:
init.vim/vimrc/ginit.vim: Calls config/main.vim
config/main.vim: sets g:_spacevim_root_dir. Sets runtimepath (though this doesn't
  seem to be its final value), then calls:
  SpaceVim#begin: Loads user init.vim. Parses cmd line args. Sets default vim
    options. Loads default layers. Sets default keybindings. Defines SP*
    commands.
  SpaceVim#custom#load: Seems to process user init.toml.
  SpaceVim#end: Seems to map everything.
config/plugins/
config/plugins_before/
autoload/
  Spacevim.vim: Sets Spacevim option defaults, defines Spacevim#begin and
    Spacevim#end
  Spacevim
    api/ (public APIs/libraries)
    layers/
    plugins/
    mapping/

### Mostly empty or miscellaneous:
  doc/ (help)
  docs/ (website)
  .Spacevim.d/: Seems like the configuration folder for the devs
  Lua/: ./spacevim/api/vim/window.lua may affect the cursor.
  ftplugin/: Something with airline and statusline.
  bin/: One-liner shell scripts calling nvr (nvim-remote) or vim
  colors/: Contains a single script that seems to define a 'Spacevim' color
           scheme that doesn't seem to be used
  mode/: Basic configuration examples. *.toml is copied to ~/.Spacevim.d/ after
  the first startup prompt

Language layer provides completion, syntax checking, find def and refs,
formatting, syntax highlighting, and indent

## Misc

s: windows leader

## Plugins of interest (in spacevim or not)

- vim-ctrlspace: per-tab windows lists, labeled tabs, and tabs list
- undotree / vim-mundo

## Help

https://gitter.im/SpaceVim/SpaceVim

## Debugging
Test in docker: https://github.com/SpaceVim/SpaceVim/tree/master/docker
Search :h spacevim for log, debug, etc.

## Sources
Project Layout
  - https://github.com/SpaceVim/SpaceVim/wiki/Project-layout
  - https://github.com/SpaceVim/SpaceVim
https://medium.com/swlh/spacevim-layers-under-the-hood-3dba2a02d13a
