---
title: "Vim mapping"
---

# Plug

I assumed only key presses in the right hand side could be remapped. But
that's not true. At least <plug>command can be used on the LHS of a
mapping. Furthermore,
they don't require an opening : and closing <CR> to execute. <plug> also
serves as a convention for a public API. <plug> followed by scriptname
and then by function name is most likely unique, and since there's no
scope specified (unlike s:), the function will be globally available
for use outside of a script.
https://www.reddit.com/r/vim/comments/78izt4/please_help_understand_how_to_use_plug_mapping/
https://www.reddit.com/r/vim/comments/bgf3zt/why_should_i_use_plug_in_my_mappings_instead_of/
Note that you can have separate mappings of e.g. xx and yy, then map
something to xxyy to execute both mappings. And <plug>anything counts as
xx or yy. See the first two examples of the following link. The second is clearer
at first glance, but they are actually equivlent conceptually:
https://www.reddit.com/r/vim/comments/c31nrf/map_a_key_to_combination_of_some_plug_and_the_key/
Anyway, this is why we use nmap with <plug>something, because typically <plug><something> is
mapped to a function call or something else that we want our user-level

See coc.nvim for examples of mappings to <Plug>. These are themselves mapped to function calls
